project('tufo_afm', 'c', meson_version: '>=1.1', default_options: ['c_std=c23'])

src=[]
inc=[]

c_args=[
'-Wall',
'-Wextra']

c_link_args=[]

subdir('tufo_core')
subdir('interface')
subdir('CMSIS')
subdir('external')
subdir('boards')

#build executable
executable(meson.project_name(),
src,
include_directories: inc,
name_suffix: 'elf',
c_args: c_args,
link_args: c_link_args
)

elf_file='@BUILD_ROOT@/' + meson.project_name() + '.elf'
pyocd_config = '--config=' + '@SOURCE_ROOT@' + '/pyocd.yaml'
run_target('flash', command: ['pyocd', 'flash', elf_file, pyocd_config])